modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/Carbonateds/Forge-Tutorial/issues"
[[mods]]
modId="tutorial"
version="1.19-0.0.1.0"
displayName="Tutorial Mod"
displayURL="https://github.com/Carbonateds/Forge-Tutorial"
authors="Carbonate, and his love"
description='''
This is the Example Mod of the Forge Mod Development Tutorial.
'''